#ifdef COLUMNDEF

COLUMNDEF(	EVENT_COMBO		)
COLUMNDEF(	CHANNEL_COMBO	)
COLUMNDEF(	CONTROL_EDIT	)
COLUMNDEF(	VAL_SLIDER		)
COLUMNDEF(	VAL_EDIT		)
COLUMNDEF(	VAL_BTN			)

#endif COLUMNDEF
#undef COLUMNDEF
